import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom'; 


function HeroSection() {
  const navigate = useNavigate(); // For navigation after submission

  const handleGenerateRecipe = (e) => {
    e.preventDefault();
    navigate(`/home`);
  };

  return (
    <section className="relative h-screen flex items-center justify-center text-center overflow-hidden bg-white text-white">

      <div className="relative z-10 p-4 max-w-4xl mx-auto">
        {/* Headline */}
        <motion.h1
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="text-5xl md:text-7xl font-extrabold mb-4 leading-tight text-yellow-400 tracking-tight"
        >
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-500">
            Unleash Your Inner Chef.
          </span>
          <br className="hidden md:block" /> Instantly.
        </motion.h1>

        <motion.p
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, ease: "easeOut", delay: 0.2 }}
          className="text-lg md:text-xl text-gray-900 mb-8 max-w-2xl mx-auto"
        >
          Transform your ingredients into gourmet meals with personalized recipes
          generated by advanced AI. Effortless cooking, endless inspiration.
        </motion.p>

        {/* Call to Action / Input Area */}
        <motion.form
          onSubmit={handleGenerateRecipe}
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, ease: "easeOut", delay: 0.4 }}
          className="flex flex-col md:flex-row items-center justify-center gap-4 px-4"
        >
          
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            type="submit"
            // Changed button gradient to orange/red tones
            className="w-full md:w-auto px-8 py-4 bg-gradient-to-r from-orange-500 to-red-600 text-white font-bold rounded-xl shadow-lg hover:from-orange-600 hover:to-red-700 transition-all duration-300"
          >
            Generate My First Recipe
          </motion.button>
        </motion.form>

        {/* Optional: Subtle social proof or feature highlights */}
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, ease: "easeOut", delay: 0.6 }}
          className="mt-12 text-gray-400 text-sm flex items-center justify-center space-x-4"
        >
          <span className="flex items-center">
            <svg className="w-5 h-5 mr-2 text-amber-400" fill="currentColor" viewBox="0 0 20 20"><path d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" fillRule="evenodd"></path></svg>
            AI-Powered
          </span>
          <span className="flex items-center">
            <svg className="w-5 h-5 mr-2 text-orange-400" fill="currentColor" viewBox="0 0 20 20"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            Personalized
          </span>
          <span className="flex items-center">
            <svg className="w-5 h-5 mr-2 text-red-400" fill="currentColor" viewBox="0 0 20 20"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 110-6 3 3 0 010 6z"></path></svg>
            Save Favorites
          </span>
        </motion.div>
      </div>
    </section>
  );
}

export default HeroSection;